import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	manifest: "/manifest.json",
	themeColor: "#f69435",
	icons: [
			"/icon-192x192.png",
			"/icon-256x256.png",
			"/icon-384x384.png",
			"/icon-512x512.png",
	],
  appleWebApp: {
    
  }
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<Head>

      </Head>
			<body className={inter.className}>{children}</body>
		</html>
	);
}
